name: CLI CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install
        run: pip install -e .
      - name: Lint
        run: python -m compileall spotrender
